# Generated by Django 6.0.7 on 2026-08-10 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_message_id__isnull", False)),
                fields=("conversation", "sender", "client_message_id"),
                name="unique_client_message_per_sender",
            ),
        ),
    ]
